### ISSUE TITLE
is PinNames.h still necessary here?

### ISSUE THREAD

**Issue by jrobeson** [ARMmbed/mbed-hal-nrf51dk#4]
I'm a little confused about seeing pins defined in nrf51dk-gcc (in module.json), but also here in the hal.  My naive thinking is that it should be in the hal, but in module.json.   So what is the approach here?

**Comment by rgrover** [comment]
having pin names in module.json mean that it is possible to derive alternate versions of a platform relatively cheaply. Pins in the HAL apply more to the chip.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1426

**Comment by rgrover** [comment]
please re-open this if you need further clarification.
